/* NOTÍCIA ES - MATÉRIAS EDITORIAIS PRÓPRIAS / RODADA 31 */
const materiasEditoriais31 = [
  {
    id: 2026082946,
    slug: "flavio-estreia-tv-voto-feminino-lula-ataques-eleicoes-2026",
    titulo: "Flávio estreia na TV mirando voto feminino, enquanto Lula abre ofensiva direta na campanha presidencial",
    categoria: "Política Nacional",
    data: "2026-08-29",
    imagem: "https://imagens.ebc.com.br/PPr0kEnRYqIEk2gj7mhWFFeJ3bo=/1600x800/https://agenciabrasil.ebc.com.br/sites/default/files/thumbnails/image/2026/07/31/eleicoes-2026-banner.png?itok=QAY_LqlL",
    resumo: "Primeiro programa presidencial no horário eleitoral expôs estratégias distintas: Flávio Bolsonaro buscou ampliar diálogo com mulheres e eleitores moderados, enquanto Lula reforçou realizações e elevou o tom contra o principal adversário.",
    conteudo: `<p><strong>A estreia do horário eleitoral presidencial neste sábado (29) colocou em evidência as duas estratégias que devem organizar a fase mais intensa da campanha de 2026. Flávio Bolsonaro (PL) usou parte importante de seus 4 minutos e 20 segundos para apresentar uma imagem mais familiar, buscar aproximação com o eleitorado feminino e falar de violência, economia e custo de vida. Luiz Inácio Lula da Silva (PT), com 5 minutos e 31 segundos, combinou defesa do próprio governo com ataques diretos ao adversário. A propaganda começou no rádio pela manhã e chegou à televisão no início da tarde, abrindo uma etapa em que as campanhas passam a disputar diariamente eleitores menos engajados nas redes sociais.</strong></p>
<p>A cobertura das agendas dos presidenciáveis na quinta-feira (27), publicada pela Agência Brasil, serviu como gatilho para esta reportagem. O Notícia ES refez a apuração a partir da estreia efetiva do horário eleitoral, das regras divulgadas pela Justiça Eleitoral e de reportagens independentes publicadas neste sábado.</p>
<h2>Flávio tenta ampliar a candidatura para além da base bolsonarista</h2>
<p>O primeiro programa de Flávio Bolsonaro mostrou uma tentativa clara de falar com segmentos em que a candidatura ainda enfrenta resistência. A campanha apresentou sua esposa, Fernanda Bolsonaro, e explorou elementos familiares para construir uma imagem de maior moderação pessoal. A Folha de S.Paulo registrou que o programa buscou de forma explícita o voto feminino, um dos grupos decisivos para a eleição e historicamente mais difícil para candidaturas associadas ao bolsonarismo.</p>
<p>A estratégia não significa abandono da identidade política que levou Flávio até aqui. O programa preservou críticas ao governo Lula e destacou problemas como violência, crime organizado, endividamento das famílias e insegurança econômica. A diferença esteve no enquadramento: a campanha procurou apresentar o candidato como alguém capaz de dialogar com eleitores que concordam com parte da agenda de direita, mas mantêm reservas em relação ao estilo político de Jair Bolsonaro.</p>
<p>Essa busca por expansão ocorre num momento em que Flávio também tenta reduzir dúvidas fora do eleitorado tradicional. Nos últimos dias, ele se reuniu com banqueiros, empresários e representantes do mercado financeiro em São Paulo para apresentar propostas e discutir uma eventual gestão. A aproximação não representa apoio formal do setor financeiro, mas mostra que a campanha trabalha simultaneamente em duas frentes: ampliar confiança entre agentes econômicos e diminuir resistência entre segmentos do eleitorado.</p>
<h2>Lula usa o maior tempo para defender governo e atacar o rival</h2>
<p>Lula entrou no horário eleitoral com a maior fatia de tempo entre os candidatos à Presidência. A campanha petista tem 5 minutos e 31 segundos por bloco, resultado da coligação formada pelo PT e partidos aliados. O PL concorre isoladamente e ficou com 4 minutos e 20 segundos. Ronaldo Caiado (PSD) tem 2 minutos e 2 segundos, e Augusto Cury (Avante), 35 segundos.</p>
<p>No primeiro programa, Lula apresentou realizações de seus governos e recuperou temas sociais e econômicos que a campanha considera favoráveis. Ao mesmo tempo, lançou ataques diretos a Flávio. A Folha e a CNN registraram que a propaganda petista utilizou referências a investigações e controvérsias envolvendo o senador para aumentar a rejeição do adversário.</p>
<p>No rádio, a campanha de Lula exibiu um áudio relacionado ao banqueiro Daniel Vorcaro e voltou a mencionar episódios como as investigações sobre rachadinhas e antigas homenagens feitas por Flávio quando deputado estadual. O senador nega irregularidades e já teve investigações encerradas ou decisões favoráveis em diferentes etapas judiciais, circunstância que exige separar acusações políticas de responsabilidades efetivamente reconhecidas pela Justiça.</p>
<p>A escolha do PT mostra que a campanha vê Flávio como adversário central desde o início da propaganda. O objetivo aparente é impedir que ele consiga se apresentar ao eleitorado menos politizado apenas como uma renovação geracional da direita ou como candidato de perfil mais moderado.</p>
<h2>O horário eleitoral volta a ter peso numa disputa apertada</h2>
<p>As redes sociais transformaram profundamente as campanhas brasileiras, mas o rádio e a televisão continuam relevantes porque alcançam públicos que não acompanham diariamente a disputa política pela internet. A própria distribuição de tempo mostra a importância atribuída pelos partidos ao formato: meses antes do início oficial da propaganda, as legendas negociaram alianças também considerando o ganho de exposição em rede nacional.</p>
<p>Segundo a Justiça Eleitoral, os programas para presidente e deputado federal são exibidos às terças, quintas e sábados. Os blocos presidenciais têm 12 minutos e 30 segundos, além das inserções distribuídas ao longo da programação. O primeiro turno será realizado em 4 de outubro.</p>
<p>Uma pesquisa BTG/Nexus divulgada nesta semana e repercutida pela Folha indicou que 60% dos entrevistados disseram ter intenção de consultar propostas e programas de governo. O levantamento também encontrou diferenças entre grupos políticos, com forte interesse inclusive entre eleitores que votam principalmente para impedir a vitória do adversário. Esse dado ajuda a explicar por que as campanhas estão investindo tanto na construção de mensagens destinadas a quem ainda pode mudar de posição.</p>
<h2>Mulheres e indecisos viram terreno decisivo</h2>
<p>O primeiro programa de Flávio também sinaliza onde sua campanha enxerga espaço para crescimento. Pesquisas eleitorais divulgadas ao longo do ano mostram diferenças relevantes entre homens e mulheres na disputa presidencial. A presença de Fernanda no programa e o esforço para apresentar uma imagem familiar não parecem casuais: são instrumentos para tentar reduzir uma desvantagem que pode decidir o segundo turno.</p>
<p>Lula também intensificou sua agenda voltada às mulheres neste sábado. Em Belo Horizonte, participou de um ato no qual defendeu o fim da escala 6x1 e destacou políticas destinadas ao público feminino. Isso mostra que os dois principais candidatos disputam o mesmo segmento por caminhos diferentes.</p>
<p>Ao mesmo tempo, ambos procuram o eleitor menos ideológico. A Folha descreveu esse grupo como eleitor-pêndulo, parcela que não se identifica integralmente com nenhum dos polos e pode definir uma eleição equilibrada. Lula tenta atraí-lo com a memória de políticas sociais e resultados de governo. Flávio aposta em uma combinação de renovação, segurança pública, críticas econômicas e esforço de moderação.</p>
<h2>A campanha entra numa fase mais dura</h2>
<p>A estreia do horário eleitoral indica que a disputa tende a ficar mais agressiva nas próximas semanas. A campanha petista já decidiu explorar vulnerabilidades do adversário. Flávio, por sua vez, começou a responder com críticas ao governo e deve aprofundar temas como segurança, dívida pública, inflação percebida pelas famílias e investigações envolvendo pessoas próximas ao presidente.</p>
<p>Ronaldo Caiado e Augusto Cury tentam romper a polarização com espaços menores. Caiado usa sua experiência em Goiás e a segurança pública como principal vitrine. Cury procura se apresentar como alternativa de diálogo e pacificação. O desafio dos dois é transformar poucos minutos de exposição em crescimento suficiente para ameaçar a concentração da disputa em Lula e Flávio.</p>
<p><strong>O primeiro sábado de propaganda deixou a linha de batalha mais clara. Lula aposta no peso da máquina política, no maior tempo de televisão e na desconstrução do principal rival. Flávio tenta ampliar sua candidatura para além do eleitor bolsonarista tradicional, especialmente entre mulheres, moderados e setores econômicos. A partir de agora, cada programa será menos uma apresentação e mais uma disputa direta por quem ainda não decidiu o voto.</strong></p>
<h2>Fontes da apuração</h2><ul>
<li><a href="https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/veja-como-foi-quinta-feira-27-dos-candidatos-presidente" target="_blank" rel="noopener noreferrer">Agência Brasil: pauta original e agenda dos presidenciáveis</a></li>
<li><a href="https://agenciabrasil.ebc.com.br/justica/noticia/2026-08/horario-eleitoral-no-radio-e-tv-comeca-nesta-sexta-feira" target="_blank" rel="noopener noreferrer">Agência Brasil: regras e divisão do horário eleitoral</a></li>
<li><a href="https://www1.folha.uol.com.br/poder/2026/08/lula-diz-que-enfrenta-poderosos-e-flavio-bolsonaro-busca-voto-feminino-em-primeiro-programa-na-tv.shtml" target="_blank" rel="noopener noreferrer">Folha de S.Paulo: estreia dos programas presidenciais na televisão</a></li>
<li><a href="https://www1.folha.uol.com.br/poder/2026/08/campanha-presidencial-no-radio-comeca-com-ataques-entre-lula-e-flavio.shtml" target="_blank" rel="noopener noreferrer">Folha de S.Paulo: estreia da propaganda presidencial no rádio</a></li>
<li><a href="https://www.cnnbrasil.com.br/eleicoes/lula-e-flavio-trocam-ataques-em-estreia-de-campanha-presidencial-no-radio/" target="_blank" rel="noopener noreferrer">CNN Brasil: confronto entre as campanhas no primeiro programa</a></li>
</ul>`,
    autor: "Redação Notícia ES",
    fonteNome: "Agência Brasil - Política",
    fonteUrl: "https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/veja-como-foi-quinta-feira-27-dos-candidatos-presidente",
    fontes: [
      "https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/veja-como-foi-quinta-feira-27-dos-candidatos-presidente",
      "https://agenciabrasil.ebc.com.br/justica/noticia/2026-08/horario-eleitoral-no-radio-e-tv-comeca-nesta-sexta-feira",
      "https://www1.folha.uol.com.br/poder/2026/08/lula-diz-que-enfrenta-poderosos-e-flavio-bolsonaro-busca-voto-feminino-em-primeiro-programa-na-tv.shtml",
      "https://www1.folha.uol.com.br/poder/2026/08/campanha-presidencial-no-radio-comeca-com-ataques-entre-lula-e-flavio.shtml",
      "https://www.cnnbrasil.com.br/eleicoes/lula-e-flavio-trocam-ataques-em-estreia-de-campanha-presidencial-no-radio/"
    ],
    editorial: true
  }
];
if (typeof noticias !== "undefined") noticias.unshift(...materiasEditoriais31);
