/* NOTÍCIA ES - MATÉRIA EDITORIAL PRÓPRIA / 11 DE SETEMBRO DE 2026 */
const materiasEditoriais38 = [
  {
    id: 11092026103000,
    slug: "mendonca-abre-arquivo-mae-master-julgamento-moraes",
    titulo: "Mendonça abre o arquivo-mãe do caso Master antes do julgamento sobre Moraes",
    categoria: "Política Nacional",
    data: "2026-09-11",
    publicadoEm: "2026-09-11T10:30:00-03:00",
    imagem: "/imagens/og/mendonca-arquivo-mae-master-capa.jpg?v=20260911-1",
    imagemX: "/imagens/og/mendonca-arquivo-mae-master-x-1200x628.jpg?v=20260911-1",
    imagemLargura: 1600,
    imagemAltura: 800,
    imagemXLargura: 1200,
    imagemXAltura: 628,
    legendaImagem: "André Mendonça retira o sigilo da PET 15.556 e entrega aos ministros o arquivo central da Operação Compliance Zero no Supremo",
    resumo: "Relator entrega aos gabinetes a PET 15.556 e processos relacionados antes da sessão de 15 de setembro, quando o STF decidirá o destino do relatório da PF sobre mensagens de Vorcaro envolvendo Alexandre de Moraes.",
    conteudo: `<p><strong>O ministro André Mendonça retirou o sigilo da PET 15.556, peça central da Operação Compliance Zero no Supremo Tribunal Federal, e determinou o envio de cópia integral do processo e de procedimentos relacionados à Presidência e aos gabinetes da Corte. A decisão foi tomada na noite de 10 de setembro de 2026, a pedido do presidente do STF, Edson Fachin, cinco dias antes da sessão extraordinária marcada para terça-feira, 15 de setembro, às 10h. O plenário analisará a PET 16.662, ramo que reúne o relatório da Polícia Federal sobre mensagens de Daniel Vorcaro envolvendo Alexandre de Moraes.</strong></p>
<p>Mendonça atendeu às duas providências solicitadas por Fachin no mesmo expediente: remeter, em HD, a íntegra da PET 15.556 e de tudo o que nela estiver contido ou a ela relacionado; e levantar o sigilo da peça principal, preservando apenas diligências cujo segredo seja indispensável ao cumprimento das medidas.</p>
<p>O relator registrou que agia “em harmonia à solicitação formulada pelo eminente Presidente” e relacionou o conjunto encaminhado: PET 15.556, INQ 5.026, RCL 88.121, PET 15.198, INQ 5.035, PET 15.478, PET 15.504, PET 15.562, PET 15.563, PET 15.693, PET 15.976, PET 15.977, PET 15.978, PET 16.019 e PET 16.662.</p>
<p>O movimento tem uma razão institucional direta. Fachin não queria que os ministros votassem sem conhecer a origem do material submetido ao plenário. Também não queria que a Corte inteira dependesse de um arquivo acessível apenas ao relator. A abertura da peça principal tornou-se condição prática para o julgamento.</p>
<p>O levantamento, porém, não abriu todo o dossiê do Banco Master. Ficaram fora o financiamento do filme “Dark Horse” e as conversas em que Flávio Bolsonaro pede dinheiro a Vorcaro; a linha atribuída ao senador Ciro Nogueira; a apuração que levou à prisão do ex-presidente do BRB Paulo Henrique Costa; e a fase da Rioprevidência relacionada ao ex-governador Cláudio Castro. O material liberado concentra o núcleo diretamente ligado à crise entre ministros.</p>

<h2>O que é a PET 15.556</h2>
<p>A PET 15.556 tem o número único 0165738-43.2026.1.00.0000. Foi protocolada em 27 de fevereiro de 2026, ficou sob relatoria de André Mendonça por prevenção com o INQ 5.026 e teve como requerente um delegado da Polícia Federal. Na capa, o assunto registrado é prisão preventiva. O processo eletrônico é público e envolve réu preso.</p>
<p>A petição não é um inquérito. Ela funciona como veículo cautelar da terceira fase da Operação Compliance Zero. A PF apresentou a representação, Mendonça despachou em 3 de março, a operação foi às ruas no dia 4 e, em 5 de março, Vorcaro foi levado à penitenciária federal de Brasília.</p>
<p>A decisão, posteriormente referendada pela Segunda Turma, decretou a prisão preventiva de quatro pessoas e medidas cautelares contra outras quatro. A investigação descreveu uma organização criminosa armada dividida em quatro núcleos: fraude contra o sistema financeiro; corrupção institucional, com cooptação de pessoas do Banco Central; ocultação patrimonial e lavagem por meio de empresas interpostas da família; e intimidação e obstrução, grupo identificado primeiro como “A Turma” e depois como “Os Meninos”.</p>
<p>Segundo a Polícia Federal e o relator, Vorcaro ocupava o centro dos quatro núcleos. Foram presos ele, o cunhado Fabiano Zettel, Luiz Phillipi Machado de Moraes Mourão, identificado como “Sicário” e depois morto sob custódia, e Marilson Roseno da Silva, policial federal aposentado apontado como líder operacional de “A Turma”.</p>
<p>Receberam medidas cautelares Paulo Sérgio Neves de Souza e Belline Santana, ambos do Departamento de Supervisão Bancária do Banco Central; Leonardo Palhares, da Varajo; e Ana Cláudia Queiroz de Paiva. Super Empreendimentos, Moriah Asset, King Participações, King Motors e Varajo Consultoria tiveram atividades suspensas.</p>
<p>A Segunda Turma confirmou a decisão por unanimidade em sessão virtual realizada entre 13 e 20 de março, com perda de objeto em relação a Mourão. Dias Toffoli declarou suspeição e não participou. Gilmar Mendes acompanhou o resultado com ressalva, criticando o uso de expressões como “clamor social” e “confiança na Justiça” por considerá-las conceitos abertos. A prisão preventiva de Vorcaro, Zettel e Marilson deixou de ser uma decisão individual e passou a contar com acórdão do colegiado.</p>
<p>A PET 15.556 continuou produzindo atos depois de março. Autorizou a oitiva de Vorcaro pela Comissão de Valores Mobiliários na cadeia, determinou manifestação da PF sobre o espelhamento dos aparelhos de Paulo Sérgio e desentranhou peças para novas petições. Em 24 de agosto, na peça 534 dos mesmos autos, Mendonça intimou a polícia a atualizar a apuração da rede de influência. A resposta, entregue em 27 de agosto, transformou-se na PET 16.662. É por isso que Fachin se refere a “procedimentos contidos ou relacionados à Pet 15.556”.</p>

<h2>O feixe de processos que estava sob sigilo</h2>
<p>A Compliance Zero no Supremo está distribuída em um conjunto de processos ligados por prevenção. O INQ 5.026 funciona como âncora e trata da tentativa de venda do Master ao BRB e da fraude financeira. A RCL 88.121 é a reclamação da defesa que ajudou a levar o caso da 10ª Vara Federal do Distrito Federal ao STF, ainda sob Toffoli. A PET 15.198 trata da perícia de aproximadamente cem aparelhos apreendidos. O INQ 5.035 e a PET 15.478, relativa à quebra bancária e fiscal de Vorcaro e Augusto Ferreira Lima em 18 de fevereiro, prepararam o terreno para as fases posteriores.</p>
<p>Na semana entre 27 de fevereiro e 4 de março formou-se o núcleo cautelar. A PET 15.504 já aparecia na certidão de prevenção quando a PET 15.556 foi aberta. A PET 15.562, protocolada em 2 de março, reuniu 19 mandados de busca contra os mesmos investigados, além de Luis Felipe Woyceichoski e empresas do bloco Super, Moriah e King. A PET 15.563 tratou de medidas assecuratórias e bloqueou patrimônio das empresas e dos dois servidores do Banco Central citados no caso.</p>
<p>Depois, o relator desmembrou outras frentes. A PET 15.693 e o conjunto formado pelas PETs 15.976, 15.977, 15.978 e 16.019 abrangem “A Turma”, Henrique Vorcaro, pai do banqueiro, Felipe Cançado Vorcaro, primo, e desdobramentos relacionados à intimidação. Em junho, a Segunda Turma manteve as prisões de Henrique e Felipe por três votos a um. Gilmar Mendes defendeu prisão domiciliar para o pai e soltura do primo; Luiz Fux e Nunes Marques acompanharam Mendonça. Toffoli novamente não participou. A PET 16.662 é o desmembramento mais recente tornado público, com o relatório que cita Moraes.</p>

<h2>O grupo de WhatsApp “Master”</h2>
<p>Entre os elementos descritos no material está o grupo de WhatsApp chamado “Master”. Ele não deve ser confundido com “A Turma” nem com “INFO - BRB”. O grupo reunia Daniel Vorcaro, Belline Santana, chefe do Desup, e Paulo Sérgio Neves de Souza, chefe-adjunto do mesmo departamento. De um lado estava o dono do banco regulado. Do outro, dois agentes ligados à estrutura que deveria supervisioná-lo.</p>
<p>Belline criou o grupo em 2 de outubro de 2025, 47 dias antes da liquidação do banco. Escreveu: “Boa tarde. Criei esse grupo, no intuito e facilitar nossa interlocução.” Vorcaro respondeu: “Ok obrigado.” Na sequência, Belline revisou o ofício que o banco enviaria ao próprio Banco Central e sugeriu retirar a palavra “Difis” para “evitar ruídos desnecessários”.</p>
<p>Antes da criação do grupo, em 17 de fevereiro de 2025, Paulo Sérgio já havia avisado Vorcaro que uma movimentação de R$ 488,8 milhões para fora do Fundo Reag Growth 95 e outra de R$ 545,5 milhões para a Master Holding haviam entrado no filtro de monitoramento do Banco Central. A mensagem dizia: “Favor verificar e me ligar.”</p>
<p>No fim de outubro e no início de novembro de 2025, os três discutiram carta ao BTG, ofício sobre cessão de carteira ao BRB, bloqueio da Mastercard no Will Bank e o relato de que pessoas de dentro do Banco Central, descritas como amigas, teriam falado em pressão máxima contra o Master.</p>
<p>Em 17 de novembro, véspera da liquidação e da primeira prisão, Paulo Sérgio escreveu: “Bom dia Daniel! Semana decisiva.” Vorcaro perguntou: “Alguma novidade? Ligo para o Ailton?” Paulo Sérgio respondeu: “Sim. Liga e insiste.” Belline acrescentou: “Considero fundamental, nesse momento.” Às 17h41, Vorcaro enviou uma reportagem sobre a venda à Fictor e escreveu: “Espero que tenha dado tempo [de] Ailton avisar o Galípolo.” No dia seguinte, o Banco Central liquidou a instituição e a PF efetuou a prisão.</p>
<p>O material atribui a outro diálogo, entre Vorcaro e Zettel, a discussão sobre pagamentos. Em dezembro de 2023, Zettel cobrou “a primeira do Belline”. Vorcaro orientou que o pagamento fosse feito pela empresa de Leonardo Palhares e reembolsado no dia seguinte. Em outubro de 2024, a PF identificou R$ 760 mil nessa ponte. Em julho de 2025, Belline teria cobrado um pagamento atrasado em um mês.</p>
<p>Segundo a apuração descrita, os recursos saíam da Super, passavam pela empresa de Palhares e chegavam ao servidor. A PF calculou pagamentos na ordem de R$ 4 milhões a Belline e R$ 8 milhões a Paulo Sérgio, além de viagens à Disney e a Paris. Vorcaro, ouvido na Papuda, admitiu ter enviado dinheiro a um “projeto social” de Belline, disse não recordar se o total era de R$ 2 milhões ou R$ 4 milhões e negou que se tratasse de vantagem indevida. As defesas negam propina.</p>
<p>Na PET 15.556, os três aparecem no núcleo de corrupção institucional. Na PET 15.563, o patrimônio deles e das empresas apontadas como ponte integra as medidas assecuratórias. Os dois agentes ligados ao Banco Central não foram presos na terceira fase. Receberam tornozeleira, afastamento e proibição de contato.</p>

<h2>O que o plenário julgará na PET 16.662</h2>
<p>A PET 16.662 tem o número único 0183355-16.2026.1.00.0000, foi protocolada em 28 de agosto e traz como requerente “de ofício”. Ela concentra o relatório Vorcaro-Moraes. Não é o processo principal da fraude bancária. Mendonça não pediu a prisão de ministro. Solicitou que o plenário decidisse o destino do material. O procurador-geral da República, Paulo Gonet, pediu a nulidade sob o argumento de que uma investigação contra integrante da Corte não poderia avançar sem passar pelo colegiado e sem observar a Lei Orgânica da Magistratura.</p>
<p>Em 9 de setembro, na PET 16.704, Fachin suspendeu a tramitação da PET 16.662. Também suspendeu a decisão de Mendonça que afastava o diretor-geral da PF, Andrei Rodrigues, e Leandro Almada, além da decisão de Flávio Dino que os reintegrava. O presidente do STF bloqueou qualquer apuração contra ministro conduzida fora da Presidência e convocou a sessão extraordinária presencial de 15 de setembro. O prazo para manifestações de Mendonça, Moraes, Gonet e Andrei termina na véspera.</p>
<p>Na prática, o plenário terá de responder a três perguntas. A ordem de 24 de agosto, expedida dentro da PET 15.556, era válida? O relatório da Polícia Federal pode ser aproveitado? Se puder, qual deve ser o destino da parte relacionada a Moraes: investigação, arquivamento ou devolução do tema à Presidência?</p>
<p>Não estão na pauta o mérito integral do caso Master, a prisão preventiva de março nem o pedido de Moraes para investigar Mendonça por suposto abuso na relatoria das PETs 15.041, ligada ao INSS e à Operação Sem Desconto, e 15.556. Fachin reservou essa discussão para outro momento. A sessão de terça será o primeiro ato colegiado da crise aberta entre os ministros nos próprios autos.</p>

<h2>O que saiu do cofre e o que permanece fechado</h2>
<p>Com o HD foram liberados aos ministros a decisão de prisão de março e o acórdão da Segunda Turma; a descrição dos quatro núcleos; o grupo “Master” e a trilha Zettel, Varajo e Belline; os 19 mandados da PET 15.562; as medidas patrimoniais da PET 15.563; a cadeia de prevenção iniciada no INQ 5.026; e o relatório isolado por Mendonça na PET 16.662.</p>
<p>Continuam protegidas as frentes referentes a “Dark Horse”, Ciro Nogueira, BRB e Paulo Henrique Costa, Rioprevidência e Cláudio Castro, além de diligências que o relator considere dependentes de sigilo operacional. Quebras bancárias e telemáticas ainda em andamento podem continuar fechadas mesmo dentro de processos classificados como públicos.</p>
<p>A divisão jurídica é decisiva. A PET 15.556 sustenta as medidas cautelares da terceira fase da Compliance Zero no STF. A PET 16.662 nasceu de um desmembramento realizado em agosto. São peças distintas. A tese de nulidade tenta ligar eventual vício da ordem de 24 de agosto à relatoria inteira. A posição contrária separa os dois momentos: a prisão preventiva de março se apoia em elementos de fevereiro, nas mensagens envolvendo os dois agentes ligados ao Banco Central e no acórdão da Segunda Turma; o relatório relacionado a Moraes surgiu depois.</p>
<p>Fachin pediu acesso amplo porque o plenário decidirá se o incidente da PET 16.662 pode existir juridicamente. Mendonça entregou a peça principal porque, sem ela, os ministros julgariam apenas um recorte. A partir da retirada do sigilo, o país passa a conhecer parte do que a Corte já tinha diante de si. O que permanece no cofre revela o limite exato do acordo institucional: colocar na mesa de terça o material necessário para julgar a crise entre ministros, sem abrir todo o caso Master.</p>`,
    autor: "Redação Notícia ES",
    entidades: [
      { tipo: "Person", nome: "André Mendonça" },
      { tipo: "Person", nome: "Edson Fachin" },
      { tipo: "Person", nome: "Alexandre de Moraes" },
      { tipo: "Person", nome: "Daniel Vorcaro" },
      { tipo: "Person", nome: "Paulo Gonet" },
      { tipo: "Organization", nome: "Supremo Tribunal Federal" },
      { tipo: "Organization", nome: "Polícia Federal" },
      { tipo: "Organization", nome: "Banco Central do Brasil" }
    ],
    aeo: [
      { pergunta: "O que André Mendonça retirou do sigilo?", resposta: "O ministro retirou o sigilo da PET 15.556 e determinou o compartilhamento de sua íntegra e de procedimentos relacionados com a Presidência e os gabinetes do STF, preservadas diligências cujo segredo seja indispensável." },
      { pergunta: "O que o STF julgará em 15 de setembro?", resposta: "O plenário analisará a validade da ordem que originou o relatório da PF, a possibilidade de aproveitar o material e o destino da parte que envolve Alexandre de Moraes." },
      { pergunta: "Todo o caso Banco Master foi aberto?", resposta: "Não. Permanecem fora do material liberado frentes como Dark Horse, Ciro Nogueira, BRB, Rioprevidência e diligências ainda protegidas por sigilo operacional." },
      { pergunta: "Qual é a diferença entre a PET 15.556 e a PET 16.662?", resposta: "A PET 15.556 concentra as medidas cautelares da terceira fase da Compliance Zero. A PET 16.662 é um desmembramento posterior que reúne o relatório da PF sobre mensagens de Vorcaro envolvendo Moraes." }
    ],
    editorial: true
  }
];
if (typeof noticias !== "undefined") noticias.unshift(...materiasEditoriais38);
