/*
  NOTÍCIA ES - BANCO DE NOTÍCIAS EM ARQUIVO ESTÁTICO
  ==================================================
  Este arquivo recebe notícias manuais e automáticas.
  O motor automático roda pelo GitHub Actions e insere novas matérias no topo.
  Para publicação manual, use publicar.html e cole o objeto logo após "const noticias = [".
*/

const noticias = [
  {
    id: 170452035257,
    slug: "homem-e-preso-10-anos-apos-ocorrencia-por-desacato-e-desobediencia-no-es",
    titulo: "Homem é preso 10 anos após ocorrência por desacato e desobediência no ES",
    categoria: "Segurança Pública",
    data: "2026-08-27",
    imagem: "imagens/auto-seguranca-publica.svg",
    resumo: "Caso ocorreu em 2016, quando condenado foi a uma unidade da PM reclamar de uma abordagem e acabou detido",
    conteudo: `<p>Caso ocorreu em 2016, quando condenado foi a uma unidade da PM reclamar de uma abordagem e acabou detido</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.agazeta.com.br/agora/homem-e-preso-10-anos-apos-ocorrencia-por-desacato-e-desobediencia-no-es-0826" target="_blank" rel="noopener noreferrer">A Gazeta - Polícia</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "A Gazeta - Polícia",
    fonteUrl: "https://www.agazeta.com.br/agora/homem-e-preso-10-anos-apos-ocorrencia-por-desacato-e-desobediencia-no-es-0826",
    automatico: true,
    coletadoEm: "2026-08-28T00:56:05.273Z"
  },
  {
    id: 272061949964,
    slug: "comerciante-foragido-por-crimes-contra-adolescentes-no-es-e-preso-em-minas-folha-vitoria",
    titulo: "Comerciante foragido por crimes contra adolescentes no ES é preso em Minas - Folha Vitória",
    categoria: "Segurança Pública",
    data: "2026-08-27",
    imagem: "imagens/auto-seguranca-publica.svg",
    resumo: "O suspeito havia sido condenado ao pagamento de R$ 1 milhão por trabalho infantil",
    conteudo: `<p>O suspeito havia sido condenado ao pagamento de R$ 1 milhão por trabalho infantil</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/policia/comerciante-foragido-por-crimes-contra-adolescentes-no-es-e-preso-em-minas/" target="_blank" rel="noopener noreferrer">Folha Vitória - Polícia</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "Folha Vitória - Polícia",
    fonteUrl: "https://www.folhavitoria.com.br/policia/comerciante-foragido-por-crimes-contra-adolescentes-no-es-e-preso-em-minas/",
    automatico: true,
    coletadoEm: "2026-08-28T00:56:05.273Z"
  },
  {
    id: 636787520386,
    slug: "catador-e-assassinado-a-tiros-em-vila-velha",
    titulo: "Catador é assassinado a tiros em Vila Velha",
    categoria: "Segurança Pública",
    data: "2026-08-27",
    imagem: "imagens/auto-seguranca-publica.svg",
    resumo: "Hiago Paradella Vicente de Oliveira, de 28 anos, foi encontrado morto na manhã desta quinta-feira (27), em Divino Espírito Santo",
    conteudo: `<p>Hiago Paradella Vicente de Oliveira, de 28 anos, foi encontrado morto na manhã desta quinta-feira (27), em Divino Espírito Santo</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/policia/catador-de-reciclaveis-e-assassinado-a-tiros-enquanto-dormia-em-vila-velha/" target="_blank" rel="noopener noreferrer">Folha Vitória - Polícia</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "Folha Vitória - Polícia",
    fonteUrl: "https://www.folhavitoria.com.br/policia/catador-de-reciclaveis-e-assassinado-a-tiros-enquanto-dormia-em-vila-velha/",
    automatico: true,
    coletadoEm: "2026-08-28T00:56:05.273Z"
  },
  {
    id: 765197209559,
    slug: "idoso-de-85-anos-condenado-por-estupro-de-vulneravel-e-preso-em-cachoeiro",
    titulo: "Idoso de 85 anos condenado por estupro de vulnerável é preso em Cachoeiro",
    categoria: "Segurança Pública",
    data: "2026-08-27",
    imagem: "imagens/auto-seguranca-publica.svg",
    resumo: "Homem foi condenado a 16 anos e oito meses de prisão e teve mandado cumprido pela Polícia Civil",
    conteudo: `<p>Homem foi condenado a 16 anos e oito meses de prisão e teve mandado cumprido pela Polícia Civil</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.agazeta.com.br/agora/idoso-de-85-anos-condenado-por-estupro-de-vulneravel-e-preso-em-cachoeiro-0826" target="_blank" rel="noopener noreferrer">A Gazeta - Polícia</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "A Gazeta - Polícia",
    fonteUrl: "https://www.agazeta.com.br/agora/idoso-de-85-anos-condenado-por-estupro-de-vulneravel-e-preso-em-cachoeiro-0826",
    automatico: true,
    coletadoEm: "2026-08-28T00:56:05.273Z"
  },
  {
    id: 380568423393,
    slug: "veja-como-foi-a-quinta-feira-27-dos-candidatos-a-presidente",
    titulo: "Veja como foi a quinta-feira (27) dos candidatos a presidente",
    categoria: "Política Nacional",
    data: "2026-08-27",
    imagem: "imagens/auto-politica-nacional.svg",
    resumo: "A agenda dos candidatos à Presidência da República nesta quinta-feira (27) incluiu sabatinas e entrevistas à imprensa, além de visitas a hospitais, abrigos, feiras e locais de trabalho. Também estão previstas atividades relacionadas a obras públicas e outras ações de campanha. >> Veja como foi o…",
    conteudo: `<p>A agenda dos candidatos à Presidência da República nesta quinta-feira (27) incluiu sabatinas e entrevistas à imprensa, além de visitas a hospitais, abrigos, feiras e locais de trabalho. Também estão previstas atividades relacionadas a obras públicas e outras ações de campanha. &gt;&gt; Veja como foi o…</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/veja-como-foi-quinta-feira-27-dos-candidatos-presidente" target="_blank" rel="noopener noreferrer">Agência Brasil - Política</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "Agência Brasil - Política",
    fonteUrl: "https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/veja-como-foi-quinta-feira-27-dos-candidatos-presidente",
    automatico: true,
    coletadoEm: "2026-08-28T00:53:48.958Z"
  },
  {
    id: 209208164019,
    slug: "flavio-tem-34-e-lula-29-entre-eleitores-do-es-no-1-turno-mostra-quaest",
    titulo: "Flávio tem 34% e Lula 29% entre eleitores do ES no 1º turno, mostra Quaest",
    categoria: "Política ES",
    data: "2026-08-27",
    imagem: "imagens/auto-politica-es.svg",
    resumo: "Considerando a margem de erro do levantamento, que é de 3 pontos para mais ou para menos, os candidatos estão tecnicamente empatados",
    conteudo: `<p>Considerando a margem de erro do levantamento, que é de 3 pontos para mais ou para menos, os candidatos estão tecnicamente empatados</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.agazeta.com.br/es/politica/flavio-tem-34-e-lula-29-entre-eleitores-do-es-no-1-turno-mostra-quaest-0826" target="_blank" rel="noopener noreferrer">A Gazeta - Política</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "A Gazeta - Política",
    fonteUrl: "https://www.agazeta.com.br/es/politica/flavio-tem-34-e-lula-29-entre-eleitores-do-es-no-1-turno-mostra-quaest-0826",
    automatico: true,
    coletadoEm: "2026-08-28T00:53:48.958Z"
  },
  {
    id: 399484495978,
    slug: "quaest-rose-e-contarato-sao-os-mais-rejeitados-na-disputa-pelo-senado-no-es",
    titulo: "Quaest: Rose e Contarato são os mais rejeitados na disputa pelo Senado no ES",
    categoria: "Política ES",
    data: "2026-08-27",
    imagem: "imagens/auto-politica-es.svg",
    resumo: "Levantamento divulgado nesta quinta-feira (27) também mediu conhecimento sobre nomes na disputa e potencial de voto dos eleitores do ES",
    conteudo: `<p>Levantamento divulgado nesta quinta-feira (27) também mediu conhecimento sobre nomes na disputa e potencial de voto dos eleitores do ES</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.agazeta.com.br/es/politica/quaest-rose-e-contarato-sao-os-mais-rejeitados-na-disputa-pelo-senado-no-es-0826" target="_blank" rel="noopener noreferrer">A Gazeta - Política</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "A Gazeta - Política",
    fonteUrl: "https://www.agazeta.com.br/es/politica/quaest-rose-e-contarato-sao-os-mais-rejeitados-na-disputa-pelo-senado-no-es-0826",
    automatico: true,
    coletadoEm: "2026-08-28T00:53:48.958Z"
  },
  {
    id: 101382561992,
    slug: "candidato-ao-senado-wellington-callegari-sera-entrevistado-ao-vivo-no-folha-vitoria-folha-vitoria",
    titulo: "Candidato ao Senado, Wellington Callegari será entrevistado ao vivo no Folha Vitória - Folha Vitória",
    categoria: "Política ES",
    data: "2026-08-27",
    imagem: "imagens/auto-politica-es.svg",
    resumo: "Entrevista com o candidato será transmitida ao vivo pelo Youtube do Folha Vitória, nesta sexta-feira (28), às 9h15",
    conteudo: `<p>Entrevista com o candidato será transmitida ao vivo pelo Youtube do Folha Vitória, nesta sexta-feira (28), às 9h15</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/eleicoes/candidato-ao-senado-wellington-callegari-sera-entrevistado-ao-vivo-no-folha-vitoria/" target="_blank" rel="noopener noreferrer">Folha Vitória - Política</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "Folha Vitória - Política",
    fonteUrl: "https://www.folhavitoria.com.br/eleicoes/candidato-ao-senado-wellington-callegari-sera-entrevistado-ao-vivo-no-folha-vitoria/",
    automatico: true,
    coletadoEm: "2026-08-28T00:53:48.958Z"
  },
  {
    id: 423762896477,
    slug: "relator-da-ccj-do-senado-vota-a-favor-da-pec-do-fim-da-escala-6x1",
    titulo: "Relator da CCJ do Senado vota a favor da PEC do fim da escala 6x1",
    categoria: "Política Nacional",
    data: "2026-08-27",
    imagem: "imagens/auto-politica-nacional.svg",
    resumo: "O senador Omar Aziz (PSD-AM) apresentou, nesta quinta-feira (27), o relatório da PEC 221/2019, que acaba com a escala 6x1 e reduz a jornada máxima de trabalho para 40 horas semanais no Brasil. Como o próprio parlamentar já havia anunciado anteriormente, ele manteve integralmente o texto aprovado…",
    conteudo: `<p>O senador Omar Aziz (PSD-AM) apresentou, nesta quinta-feira (27), o relatório da PEC 221/2019, que acaba com a escala 6x1 e reduz a jornada máxima de trabalho para 40 horas semanais no Brasil. Como o próprio parlamentar já havia anunciado anteriormente, ele manteve integralmente o texto aprovado…</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/relator-da-ccj-do-senado-vota-favor-da-pec-do-fim-da-escala-6x1" target="_blank" rel="noopener noreferrer">Agência Brasil - Política</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "Agência Brasil - Política",
    fonteUrl: "https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/relator-da-ccj-do-senado-vota-favor-da-pec-do-fim-da-escala-6x1",
    automatico: true,
    coletadoEm: "2026-08-28T00:53:48.958Z"
  },
  {
    id: 559715546640,
    slug: "ricardo-ferraco-preve-escolas-integrais-e-aeroporto",
    titulo: "Ricardo Ferraço prevê escolas integrais e aeroporto",
    categoria: "Política ES",
    data: "2026-08-27",
    imagem: "imagens/auto-politica-es.svg",
    resumo: "O plano de governo inclui propostas para 19 áreas, como segurança pública, educação, saúde, meio ambiente, gestão, entre outras",
    conteudo: `<p>O plano de governo inclui propostas para 19 áreas, como segurança pública, educação, saúde, meio ambiente, gestão, entre outras</p><p>O Notícia ES identificou esta atualização em uma fonte monitorada pelo motor automático do portal. Para preservar contexto, autoria e eventuais atualizações posteriores, o texto integral permanece na publicação original.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/eleicoes/plano-de-ricardo-ferraco-preve-escolas-integrais-hospital-veterinario-e-aeroporto-de-cargas/" target="_blank" rel="noopener noreferrer">Folha Vitória - Política</a>.</p>`,
    autor: "Redação Notícia ES",
    fonteNome: "Folha Vitória - Política",
    fonteUrl: "https://www.folhavitoria.com.br/eleicoes/plano-de-ricardo-ferraco-preve-escolas-integrais-hospital-veterinario-e-aeroporto-de-cargas/",
    automatico: true,
    coletadoEm: "2026-08-28T00:53:48.958Z"
  },
  {
    id: 14,
    slug: "senado-es-tem-11-candidatos-para-duas-vagas-em-2026",
    titulo: "Senado no ES tem 11 candidatos para duas vagas nas Eleições 2026",
    categoria: "Política ES",
    data: "2026-08-27",
    imagem: "https://placehold.co/1200x675/17324d/ffffff?text=Senado+ES+2026",
    resumo: "Com os registros encerrados, onze nomes disputam as duas cadeiras do Espírito Santo no Senado nas eleições de 4 de outubro.",
    conteudo: `<p>A disputa pelas duas vagas do Espírito Santo no Senado Federal já tem onze candidaturas registradas para as Eleições 2026. O pleito será realizado em 4 de outubro, e cada eleitor poderá votar em dois nomes para a Casa.</p><p>Entre os candidatos estão políticos com passagem pelo Congresso, ex-prefeitos, parlamentares e nomes ligados à segurança pública. A composição definitiva das chapas e as fotos oficiais foram registradas na Justiça Eleitoral após o encerramento do prazo de candidaturas.</p><p>A corrida ao Senado tende a ocupar espaço central na campanha capixaba porque, além das duas vagas em disputa, o mandato é de oito anos e os eleitos participarão de votações nacionais sobre segurança, economia, reformas constitucionais e indicações de autoridades.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/eleicoes/eleicoes-2026-no-es-veja-a-foto-de-urna-dos-candidatos-ao-senado/" target="_blank" rel="noopener noreferrer">Folha Vitória</a>, com dados das candidaturas registradas no TSE.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 13,
    slug: "familias-de-desaparecidos-podem-coletar-dna-gratuitamente-no-es",
    titulo: "Famílias de desaparecidos podem fazer coleta gratuita de DNA no ES",
    categoria: "Segurança Pública",
    data: "2026-08-27",
    imagem: "https://placehold.co/1200x675/7a1830/ffffff?text=Seguran%C3%A7a+P%C3%BAblica",
    resumo: "Mobilização nacional permite que familiares de pessoas desaparecidas forneçam material genético gratuitamente no Espírito Santo até esta sexta-feira.",
    conteudo: `<p>Familiares de pessoas desaparecidas no Espírito Santo podem participar gratuitamente da Mobilização Nacional de Coleta de DNA, iniciativa voltada à ampliação dos bancos genéticos usados na identificação de pessoas desaparecidas e restos mortais ainda sem identificação.</p><p>No Estado, a coleta está disponível até esta sexta-feira, 28 de agosto. O material genético dos familiares é comparado com perfis existentes nos bancos oficiais, o que pode ajudar investigações em andamento e permitir novas identificações mesmo em casos antigos.</p><p>A iniciativa integra um esforço nacional de segurança pública e perícia. A orientação é que os interessados procurem os pontos indicados pelas autoridades estaduais levando documento de identificação e, quando disponível, informações relacionadas ao desaparecimento.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/policia/familias-de-desaparecidos-podem-fazer-coleta-de-dna-de-graca-no-es-veja-locais/" target="_blank" rel="noopener noreferrer">Folha Vitória</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 12,
    slug: "tse-aprova-forcas-federais-para-eleicoes-em-cinco-estados",
    titulo: "TSE aprova forças federais para reforçar segurança das eleições em cinco estados",
    categoria: "Política Nacional",
    data: "2026-08-27",
    imagem: "https://placehold.co/1200x675/202734/ffffff?text=Elei%C3%A7%C3%B5es+2026",
    resumo: "Medida autoriza apoio das Forças Armadas em mais de cem municípios de Tocantins, Piauí, Ceará, Acre e Rio de Janeiro no primeiro turno.",
    conteudo: `<p>O Tribunal Superior Eleitoral aprovou por unanimidade o envio de forças federais para reforçar a segurança e a ordem pública durante o primeiro turno das Eleições 2026 em mais de uma centena de municípios.</p><p>A autorização alcança localidades do Tocantins, Piauí, Ceará, Acre e Rio de Janeiro, incluindo capitais, aldeias indígenas, regiões de fronteira, municípios distantes e áreas ribeirinhas. O primeiro turno está marcado para 4 de outubro.</p><p>Depois da autorização do TSE, os pedidos seguem para o Ministério da Defesa, responsável pelo planejamento da atuação das Forças Armadas. Além do apoio à segurança, militares tradicionalmente auxiliam a Justiça Eleitoral no transporte de urnas, materiais e equipes para áreas de difícil acesso.</p><p><strong>Fonte:</strong> <a href="https://www.tse.jus.br/comunicacao/noticias/2026/Agosto/tse-aprova-forcas-federais-para-reforcar-seguranca-das-eleicoes-em-cinco-estados" target="_blank" rel="noopener noreferrer">Tribunal Superior Eleitoral</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 11,
    slug: "senado-tem-relatorio-favoravel-ao-fim-da-escala-6x1",
    titulo: "Fim da escala 6x1 já tem relatório favorável na CCJ do Senado",
    categoria: "Política Nacional",
    data: "2026-08-27",
    imagem: "https://placehold.co/1200x675/34495e/ffffff?text=Congresso+Nacional",
    resumo: "Proposta reduz a jornada máxima para 40 horas semanais e garante dois dias de repouso, com implementação progressiva prevista no texto.",
    conteudo: `<p>A proposta de emenda à Constituição que põe fim à escala de trabalho 6x1 recebeu relatório favorável na Comissão de Constituição e Justiça do Senado. O tema está entre as matérias consideradas prioritárias pelo Congresso antes da fase final da campanha eleitoral.</p><p>O texto aprovado anteriormente pela Câmara reduz a carga horária máxima para 40 horas semanais e prevê dois dias de repouso semanal remunerado, sem redução salarial. A implementação seria progressiva e há regras específicas para regimes de trabalho diferenciados.</p><p>A apresentação de parecer favorável não encerra a tramitação. A proposta ainda precisa passar pelas etapas previstas no Senado para uma alteração constitucional, incluindo deliberação em plenário caso seja aprovada pela comissão.</p><p><strong>Fonte:</strong> <a href="https://www12.senado.leg.br/noticias/materias/2026/08/27/pec-do-fim-da-escala-6x1-ja-conta-com-relatorio-favoravel-na-ccj" target="_blank" rel="noopener noreferrer">Agência Senado</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 10,
    slug: "tse-e-google-lancam-ferramenta-contra-deepfakes-na-eleicao",
    titulo: "TSE e Google ampliam proteção de candidatos contra deepfakes nas eleições",
    categoria: "Política Nacional",
    data: "2026-08-26",
    imagem: "https://placehold.co/1200x675/3d5366/ffffff?text=IA+e+Elei%C3%A7%C3%B5es",
    resumo: "Parceria incentiva candidatos a usar ferramenta do YouTube capaz de detectar vídeos sintéticos que reproduzam sua imagem sem autorização.",
    conteudo: `<p>O Tribunal Superior Eleitoral e o Google lançaram uma iniciativa conjunta para ampliar a identificação de conteúdos sintéticos e deepfakes que reproduzam indevidamente a imagem de candidatas e candidatos nas Eleições 2026.</p><p>A ferramenta de Detecção por Semelhanças do YouTube permite que o usuário faça uma verificação de identidade e, depois do processamento do cadastro, receba alertas sobre vídeos que aparentem reproduzir sua imagem. Caso considere o material indevido, poderá solicitar análise e eventual remoção de acordo com as políticas da plataforma.</p><p>O TSE ressalta que a tecnologia não substitui a fiscalização nem a análise humana. A parceria integra o conjunto de medidas adotadas pela Justiça Eleitoral diante do crescimento do uso de inteligência artificial generativa na campanha.</p><p><strong>Fonte:</strong> <a href="https://www.tse.jus.br/comunicacao/noticias/2026/Agosto/parceria-entre-tse-e-google-amplia-protecao-contra-uso-indevido-de-ia-nas-eleicoes" target="_blank" rel="noopener noreferrer">Tribunal Superior Eleitoral</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 9,
    slug: "congresso-define-pec-seguranca-6x1-e-outras-prioridades",
    titulo: "PEC da Segurança e fim da escala 6x1 entram nas prioridades do Congresso",
    categoria: "Política Nacional",
    data: "2026-08-26",
    imagem: "https://placehold.co/1200x675/1f3b4d/ffffff?text=Bras%C3%ADlia",
    resumo: "Presidentes do Senado e da Câmara acertaram com o Executivo uma agenda de votações para a semana de esforço concentrado antes das eleições.",
    conteudo: `<p>Os presidentes do Senado, Davi Alcolumbre, e da Câmara, Hugo Motta, acertaram com o presidente da República uma lista de matérias consideradas prioritárias para a próxima semana de votações no Congresso.</p><p>Entre os temas estão a PEC da Segurança Pública, a proposta que encerra a escala 6x1, a medida provisória sobre a chamada taxa das blusinhas, o marco legal dos minerais críticos e o regime especial de tributação para datacenters.</p><p>Na área de segurança, a PEC reorganiza aspectos do sistema nacional e trata de fontes de financiamento, incluindo recursos destinados aos fundos de segurança pública e penitenciário. O Senado prevê esforço concentrado entre 31 de agosto e 4 de setembro, antes da redução do ritmo de votações causada pela campanha eleitoral.</p><p><strong>Fonte:</strong> <a href="https://www12.senado.leg.br/noticias/materias/2026/08/26/davi-alcolumbre-acerta-prioridades-do-congresso-em-reuniao-com-lula-e-motta" target="_blank" rel="noopener noreferrer">Agência Senado</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 8,
    slug: "casagrande-defende-mudancas-stf-e-fala-sobre-bets-em-entrevista",
    titulo: "Casagrande defende mudanças no STF e fala sobre bets em entrevista eleitoral",
    categoria: "Política ES",
    data: "2026-08-26",
    imagem: "https://placehold.co/1200x675/6b2238/ffffff?text=Pol%C3%ADtica+ES",
    resumo: "Candidato ao Senado pelo ES abordou apostas, segurança e reforma do Judiciário durante série de entrevistas eleitorais.",
    conteudo: `<p>O candidato ao Senado Renato Casagrande (PSB) apresentou posições sobre segurança pública, apostas e mudanças no Poder Judiciário durante entrevista da série eleitoral promovida pelo Folha Vitória e pela TV Vitória.</p><p>Entre os temas abordados, o ex-governador defendeu mudanças na estrutura dos cargos do Supremo Tribunal Federal, com crítica ao caráter vitalício das vagas, e tratou da regulamentação das apostas. Também comentou questões relacionadas à execução penal e à segurança pública.</p><p>A entrevista faz parte de uma sequência com candidatos às duas vagas do Espírito Santo no Senado. A série busca apresentar propostas e posições dos concorrentes em temas que estarão sob responsabilidade do Congresso Nacional.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/eleicoes/casagrande-fala-sobre-bet-do-banestes-e-defende-fim-de-cargo-vitalicio-no-stf/" target="_blank" rel="noopener noreferrer">Folha Vitória</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 7,
    slug: "doze-municipios-es-recebem-nota-maxima-ranking-transparencia",
    titulo: "Doze municípios do ES recebem nota máxima em ranking de transparência",
    categoria: "Política ES",
    data: "2026-08-25",
    imagem: "https://placehold.co/1200x675/4b5965/ffffff?text=Transpar%C3%AAncia+P%C3%BAblica",
    resumo: "Levantamento avaliou práticas de transparência municipal e apontou doze cidades capixabas com nota máxima.",
    conteudo: `<p>Doze municípios do Espírito Santo alcançaram nota máxima no Ranking Capixaba de Transparência, levantamento divulgado pela Transparência Capixaba e pelo Espírito Santo em Ação.</p><p>A avaliação considera a forma como as administrações municipais disponibilizam informações públicas e ferramentas de acesso a dados. O desempenho é relevante para o acompanhamento de gastos, contratos, receitas, estrutura administrativa e outras informações de interesse do cidadão.</p><p>O resultado também reforça a importância de portais públicos atualizados e de mecanismos que permitam ao eleitor fiscalizar a gestão local. O ranking funciona como instrumento de comparação entre municípios e pode orientar melhorias em administrações que ainda apresentam lacunas.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/politica/12-municipios-do-es-recebem-nota-maxima-em-ranking-de-transparencia-veja-a-lista/" target="_blank" rel="noopener noreferrer">Folha Vitória</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 6,
    slug: "pf-investiga-fraude-inss-com-alvo-no-espirito-santo",
    titulo: "PF investiga fraude no INSS com alvo no Espírito Santo e prejuízo milionário",
    categoria: "Segurança Pública",
    data: "2026-08-25",
    imagem: "https://placehold.co/1200x675/742b35/ffffff?text=Pol%C3%ADcia+Federal",
    resumo: "Operação investiga 457 benefícios suspeitos e um prejuízo superior a R$ 86 milhões; São Gabriel da Palha esteve entre os locais das diligências.",
    conteudo: `<p>A Polícia Federal realizou diligências no Espírito Santo dentro de uma operação que investiga fraudes em benefícios do Instituto Nacional do Seguro Social destinados principalmente a idosos de baixa renda.</p><p>Segundo as informações divulgadas sobre a Operação Leste do Espinhaço, a investigação alcança 457 benefícios considerados fraudulentos e aponta prejuízo superior a R$ 86 milhões aos cofres públicos. São Gabriel da Palha, no Noroeste capixaba, esteve entre os municípios onde foram cumpridas medidas, além de cidades de Minas Gerais.</p><p>A suspeita é de atuação organizada para criação de pessoas fictícias e falsificação de documentos usados na obtenção dos benefícios. O caso segue sob investigação, e a responsabilização dos envolvidos dependerá da apuração e das decisões judiciais.</p><p><strong>Fonte:</strong> <a href="https://www.agazeta.com.br/es/policia/pf-cumpre-medidas-no-es-contra-fraude-ao-inss-em-beneficios-de-idosos-de-baixa-renda-0826" target="_blank" rel="noopener noreferrer">A Gazeta</a>.</p>`,
    autor: "Redação Notícia ES"
  },
  {
    id: 5,
    slug: "es-tem-46-candidatos-ligados-forcas-seguranca-eleicoes-2026",
    titulo: "ES tem pelo menos 46 candidatos ligados às forças de segurança nas eleições",
    categoria: "Segurança Pública",
    data: "2026-08-24",
    imagem: "https://placehold.co/1200x675/183b4e/ffffff?text=Seguran%C3%A7a+e+Elei%C3%A7%C3%B5es",
    resumo: "Policiais civis e militares, bombeiros e outros profissionais da segurança aparecem entre os candidatos registrados no Espírito Santo.",
    conteudo: `<p>O Espírito Santo terá pelo menos 46 candidatos ligados às forças de segurança nas Eleições 2026, segundo levantamento feito a partir dos registros de candidaturas disponibilizados pela Justiça Eleitoral.</p><p>O grupo reúne policiais civis, policiais militares, bombeiros militares e outros nomes com trajetória profissional vinculada à área. A presença desses candidatos mostra o peso que temas como segurança pública, valorização das carreiras, sistema prisional e combate ao crime devem ter na campanha estadual.</p><p>As candidaturas estão distribuídas entre diferentes partidos e cargos. O dado também evidencia uma tendência já observada em eleições anteriores: profissionais da segurança buscam transformar reconhecimento corporativo e atuação pública em representação política.</p><p><strong>Fonte:</strong> <a href="https://www.folhavitoria.com.br/eleicoes/policiais-bombeiros-e-militares-es-tera-mais-de-40-candidatos-ligados-a-seguranca-nas-eleicoes/" target="_blank" rel="noopener noreferrer">Folha Vitória</a>, com base em dados do TSE.</p>`,
    autor: "Redação Notícia ES"
  }
];
